modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/"

[[mods]]
modId="bluelock"
version="1.0"
displayName="Blue Lock Mod"
displayURL="https://github.com/"
credits="Created using Acode"
authors="Me"
description='''
Mod about Anime Blue Lock for 1.16.5
'''

[[dependencies.bluelock]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bluelock]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"